# The URL the site will be built for
base_url = "https://afgm-hrc.net"
generate_rss = true
compile_sass = true

title = "afgm-hrc"
description = "Hampton Roads Chapter"
highlight_code = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Mike"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"},
    {url = "$BASE_URL/getinvolved", name = "Get Involved"}
]
clean_blog_social = [
    {url = "https://twitter.com/AFGMentoring", icon="fab fa-twitter"},
    {url = "https://www.facebook.com/AFGMentoring/", icon="fab fa-facebook"},
    {url = "https://www.linkedin.com/in/michael-morgan-a67a701a8/", icon="fab fa-linkedin"},
    {url = "https://www.instagram.com/afgmentoring/", icon="fab fa-instagram"}
]
